import { z } from "zod";
import { DomainError, transaction } from "@quizarena/database";
import { snapshotFromQuiz } from "./snapshot.js";

// Quiz authoring for an account: create/edit/publish quizzes and their
// questions. Quiz-domain code, moved out of the platform database package.
const quizSchema = z.object({ title: z.string().trim().min(1).max(300), description: z.string().trim().max(10000).nullable().optional().default(null), version: z.number().int().positive().optional() }).strict();
const optionSchema = z.object({ id: z.uuid().optional(), text: z.string().trim().min(1).max(1000), isCorrect: z.boolean() }).strict();
const questionSchema = z.object({ prompt: z.string().trim().min(1).max(5000), durationSeconds: z.number().int().min(5).max(120), basePoints: z.number().int().min(100).max(10000), explanation: z.string().trim().max(10000).nullable().optional().default(null), version: z.number().int().positive().optional(), options: z.array(optionSchema).min(2).max(6) }).strict().superRefine((q, ctx) => { if (q.options.filter((o) => o.isCorrect).length !== 1) ctx.addIssue({ code: "custom", path: ["options"], message: "Exatamente uma resposta correta é obrigatória." }); });
const quizDTO = (quiz, full = false) => ({ id: quiz.id, title: quiz.title, description: quiz.description, status: quiz.status, version: quiz.version, questionCount: quiz.questions?.length ?? quiz._count?.questions ?? 0, createdAt: quiz.createdAt, updatedAt: quiz.updatedAt, publishedAt: quiz.publishedAt, ...(full ? { questions: quiz.questions.map((q) => ({ id: q.id, prompt: q.prompt, durationSeconds: q.durationSeconds, basePoints: q.basePoints, explanation: q.explanation, position: q.position, options: q.options.map((o) => ({ id: o.id, text: o.text, isCorrect: o.isCorrect, position: o.position })) })) } : {}) });

function parse(schema, value, code = "INVALID_PAYLOAD") { const result = schema.safeParse(value); if (!result.success) throw new DomainError(code, code, result.error.issues.map((issue) => ({ code: "INVALID", path: issue.path.join("."), message: issue.message }))); return result.data; }
async function owned(db, ownerId, id) { const quiz = await db.quiz.findFirst({ where: { id, ownerId }, include: { questions: { orderBy: { position: "asc" }, include: { options: { orderBy: { position: "asc" } } } } } }); if (!quiz) throw new DomainError("NOT_FOUND"); return quiz; }

// Reordering parks questions at positions above any real one (the CHECK requires position > 0
// and (quizId, position) is unique), then writes the final 1..n.
const PARKING_OFFSET = 100000;

export function createQuizAuthoring(client) {
  return {
    listQuizzes: async (ownerId) => (await client.quiz.findMany({ where: { ownerId }, include: { _count: { select: { questions: true } } }, orderBy: [{ updatedAt: "desc" }, { id: "asc" }] })).map((quiz) => quizDTO(quiz)),
    async getQuiz(ownerId, id) { return quizDTO(await owned(client, ownerId, id), true); },
    createQuiz(ownerId, input) { const data = parse(quizSchema.omit({ version: true }), input); return client.quiz.create({ data: { ownerId, title: data.title, description: data.description } }).then(quizDTO); },
    updateQuiz(ownerId, id, input) { const data = parse(quizSchema, input); return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, id); if (quiz.status !== "DRAFT") throw new DomainError("QUIZ_NOT_DRAFT"); if (data.version && data.version !== quiz.version) throw new DomainError("CONFLICT"); const result = await tx.quiz.updateMany({ where: { id, ownerId, version: quiz.version }, data: { title: data.title, description: data.description, version: { increment: 1 } } }); if (result.count !== 1) throw new DomainError("CONFLICT"); return quizDTO(await owned(tx, ownerId, id), true); }); },
    addQuestion(ownerId, quizId, input) { const data = parse(questionSchema, input); return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, quizId); if (quiz.status !== "DRAFT") throw new DomainError("QUIZ_NOT_DRAFT"); const position = quiz.questions.length + 1; await tx.question.create({ data: { quizId, position, prompt: data.prompt, durationSeconds: data.durationSeconds, basePoints: data.basePoints, explanation: data.explanation, options: { create: data.options.map((o, i) => ({ text: o.text, isCorrect: o.isCorrect, position: i + 1 })) } } }); await tx.quiz.update({ where: { id: quizId }, data: { version: { increment: 1 } } }); return quizDTO(await owned(tx, ownerId, quizId), true); }); },
    updateQuestion(ownerId, quizId, questionId, input) { const data = parse(questionSchema, input); return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, quizId); const question = quiz.questions.find((item) => item.id === questionId); if (quiz.status !== "DRAFT" || !question) throw new DomainError(quiz.status !== "DRAFT" ? "QUIZ_NOT_DRAFT" : "NOT_FOUND"); if (data.version && data.version !== quiz.version) throw new DomainError("CONFLICT"); const existingIds = new Set(question.options.map((option) => option.id)); if (data.options.some((option) => option.id && !existingIds.has(option.id)) || new Set(data.options.flatMap((option) => option.id ? [option.id] : [])).size !== data.options.filter((option) => option.id).length) throw new DomainError("INVALID_PAYLOAD"); const claimed = new Set(data.options.flatMap((option) => option.id ? [option.id] : [])); await tx.questionOption.updateMany({ where: { questionId }, data: { position: { increment: 1000 } } }); await tx.questionOption.deleteMany({ where: { questionId, id: { notIn: [...claimed] } } }); for (const [index, option] of data.options.entries()) { if (option.id) await tx.questionOption.update({ where: { id: option.id }, data: { text: option.text, isCorrect: option.isCorrect, position: index + 1 } }); else await tx.questionOption.create({ data: { questionId, text: option.text, isCorrect: option.isCorrect, position: index + 1 } }); } await tx.question.update({ where: { id: questionId }, data: { prompt: data.prompt, durationSeconds: data.durationSeconds, basePoints: data.basePoints, explanation: data.explanation } }); const changed = await tx.quiz.updateMany({ where: { id: quizId, ownerId, version: quiz.version }, data: { version: { increment: 1 } } }); if (changed.count !== 1) throw new DomainError("CONFLICT"); return quizDTO(await owned(tx, ownerId, quizId), true); }); },
    deleteQuestion(ownerId, quizId, questionId) { return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, quizId); if (quiz.status !== "DRAFT" || !quiz.questions.some((q) => q.id === questionId)) throw new DomainError(quiz.status !== "DRAFT" ? "QUIZ_NOT_DRAFT" : "NOT_FOUND"); await tx.question.delete({ where: { id: questionId } }); const remaining = quiz.questions.filter((q) => q.id !== questionId); for (const [i, q] of remaining.entries()) await tx.question.update({ where: { id: q.id }, data: { position: -(i + 1) } }); for (const [i, q] of remaining.entries()) await tx.question.update({ where: { id: q.id }, data: { position: i + 1 } }); await tx.quiz.update({ where: { id: quizId }, data: { version: { increment: 1 } } }); }); },
    reorder(ownerId, quizId, ids) { return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, quizId); if (quiz.status !== "DRAFT" || !Array.isArray(ids) || ids.length !== quiz.questions.length || new Set(ids).size !== ids.length || ids.some((id) => !quiz.questions.some((q) => q.id === id))) throw new DomainError(quiz.status !== "DRAFT" ? "QUIZ_NOT_DRAFT" : "INVALID_ORDER"); for (const [i, id] of ids.entries()) await tx.question.update({ where: { id }, data: { position: PARKING_OFFSET + i } }); for (const [i, id] of ids.entries()) await tx.question.update({ where: { id }, data: { position: i + 1 } }); await tx.quiz.update({ where: { id: quizId }, data: { version: { increment: 1 } } }); return quizDTO(await owned(tx, ownerId, quizId), true); }); },
    publish(ownerId, id) { return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, id); try { snapshotFromQuiz(quiz); } catch { throw new DomainError("QUIZ_INVALID", "QUIZ_INVALID", [{ code: "INCOMPLETE", path: "questions", message: "Complete todas as perguntas e alternativas antes de publicar." }]); } if (quiz.status === "PUBLISHED") return quizDTO(quiz, true); return quizDTO(await tx.quiz.update({ where: { id }, data: { status: "PUBLISHED", publishedAt: new Date(), version: { increment: 1 } }, include: { questions: { orderBy: { position: "asc" }, include: { options: { orderBy: { position: "asc" } } } } } }), true); }); },
    unpublish(ownerId, id) { return transaction(client, async (tx) => { await owned(tx, ownerId, id); return quizDTO(await tx.quiz.update({ where: { id }, data: { status: "DRAFT", publishedAt: null, version: { increment: 1 } } })); }); },
    remove(ownerId, id) { return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, id); if (quiz.status !== "DRAFT") throw new DomainError("QUIZ_NOT_DRAFT"); if ((await tx.quizMatchState.count({ where: { quizId: id } })) + (await tx.gameSession.count({ where: { quizId: id } }))) throw new DomainError("QUIZ_IN_USE"); await tx.quiz.delete({ where: { id } }); }); },
    async publishedOwned(ownerId) { return (await client.quiz.findMany({ where: { ownerId, status: "PUBLISHED" }, include: { _count: { select: { questions: true } } }, orderBy: { updatedAt: "desc" } })).map((quiz) => quizDTO(quiz)); },
    async publishedAll() { return (await client.quiz.findMany({ where: { status: "PUBLISHED" }, include: { _count: { select: { questions: true } }, owner: { select: { name: true } }, questions: { select: { durationSeconds: true } } }, orderBy: { updatedAt: "desc" } })).map((quiz) => ({ ...quizDTO(quiz), ownerId: quiz.ownerId, ownerName: quiz.owner.name, estimatedSeconds: quiz.questions.reduce((total, q) => total + q.durationSeconds, 0) })); },
    async buildOwnedSnapshot(ownerId, id) { return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, id); if (quiz.status !== "PUBLISHED") throw new DomainError("QUIZ_NOT_PUBLISHED"); return snapshotFromQuiz(quiz); }); },
  };
}
