"use client";
import Link from"next/link";import{useParams,useRouter}from"next/navigation";import{useCallback,useEffect,useState}from"react";import{api}from"../../../../lib/api";import styles from"../../../auth.module.css";
const blank=()=>({prompt:"",durationSeconds:30,basePoints:1000,explanation:"",options:[{text:"",isCorrect:true},{text:"",isCorrect:false}]});

export default function Editor() {
  const { id } = useParams();
  const router = useRouter();
  const [quiz, setQuiz] = useState(null);
  const [draft, setDraft] = useState(blank());
  const [editing, setEditing] = useState(null);
  const [error, setError] = useState("");
  const [saved, setSaved] = useState("");
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { setQuiz((await api(`/quizzes/${id}`)).quiz); } catch (e) { if (e.status === 401) router.replace("/login"); else setError(e.message); } }, [id, router]);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  async function act(fn) { setBusy(true); setError(""); setSaved(""); try { await fn(); await load(); setSaved("Alterações salvas."); } catch (e) { setError(e.details?.map((d) => `${d.path}: ${d.message}`).join(" ") || e.message); } finally { setBusy(false); } }
  async function metadata(event) { event.preventDefault(); const form = new FormData(event.currentTarget); await act(() => api(`/quizzes/${id}`, { method: "PATCH", body: JSON.stringify({ title: form.get("title"), description: form.get("description") || null, version: quiz.version }) })); }
  async function saveQuestion(event) { event.preventDefault(); const payload = { ...draft, durationSeconds: Number(draft.durationSeconds), basePoints: Number(draft.basePoints) }; await act(() => api(`/quizzes/${id}/questions${editing ? `/${editing}` : ""}`, { method: editing ? "PATCH" : "POST", body: JSON.stringify(payload) })); setDraft(blank()); setEditing(null); }
  function edit(question) { setEditing(question.id); setDraft({ prompt: question.prompt, durationSeconds: question.durationSeconds, basePoints: question.basePoints, explanation: question.explanation || "", options: question.options.map((option) => ({ text: option.text, isCorrect: option.isCorrect })) }); }
  async function move(index, delta) { const ids = quiz.questions.map((question) => question.id); const next = index + delta; [ids[index], ids[next]] = [ids[next], ids[index]]; await act(() => api(`/quizzes/${id}/questions/reorder`, { method: "POST", body: JSON.stringify({ ids }) })); }
  if (!quiz) return <main className={styles.shell}><p>{error || "Carregando editor…"}</p></main>;
  const editable = quiz.status === "DRAFT";
  return <main className={styles.shell}><section className={styles.card} style={{ width: "min(100%,900px)" }}>
    <header className={styles.top}><div><Link className={styles.link} href="/painel">← Painel</Link><h1>{quiz.title}</h1><p>{quiz.status} · versão {quiz.version}</p></div><div className={styles.actions}>{editable ? <button className={styles.button} disabled={busy} onClick={() => act(() => api(`/quizzes/${id}/publish`, { method: "POST", body: "{}" }))}>Publicar</button> : <button onClick={() => act(() => api(`/quizzes/${id}/unpublish`, { method: "POST", body: "{}" }))}>Despublicar</button>}<button disabled={!editable} onClick={() => { if (confirm("Excluir este quiz?")) act(async () => { await api(`/quizzes/${id}`, { method: "DELETE", body: "{}" }); router.replace("/painel"); }); }}>Excluir</button></div></header>
    <form className={styles.form} onSubmit={metadata}><div className={styles.field}><label htmlFor="title">Título</label><input id="title" name="title" defaultValue={quiz.title} disabled={!editable} required /></div><div className={styles.field}><label htmlFor="description">Descrição</label><textarea id="description" name="description" defaultValue={quiz.description || ""} disabled={!editable} /></div><button className={styles.button} disabled={!editable || busy}>Salvar dados</button></form>
    <h2>Perguntas</h2>{quiz.questions.map((question, index) => <article key={question.id}><div className={styles.top}><div><strong>{index + 1}. {question.prompt}</strong><p>{question.durationSeconds}s · {question.basePoints} pontos · {question.options.length} alternativas</p></div><div className={styles.actions}><button disabled={!editable || index === 0} onClick={() => move(index, -1)}>↑</button><button disabled={!editable || index === quiz.questions.length - 1} onClick={() => move(index, 1)}>↓</button><button disabled={!editable} onClick={() => edit(question)}>Editar</button><button disabled={!editable} onClick={() => { if (confirm("Excluir pergunta?")) act(() => api(`/quizzes/${id}/questions/${question.id}`, { method: "DELETE", body: "{}" })); }}>Excluir</button></div></div></article>)}
    {editable && <form className={styles.form} onSubmit={saveQuestion}><h2>{editing ? "Editar pergunta" : "Nova pergunta"}</h2><div className={styles.field}><label htmlFor="prompt">Enunciado</label><input id="prompt" value={draft.prompt} onChange={(e) => setDraft({ ...draft, prompt: e.target.value })} required /></div><div className={styles.top}><div className={styles.field}><label htmlFor="duration">Duração</label><input id="duration" type="number" min="5" max="120" value={draft.durationSeconds} onChange={(e) => setDraft({ ...draft, durationSeconds: e.target.value })} /></div><div className={styles.field}><label htmlFor="points">Pontos</label><input id="points" type="number" min="100" max="10000" value={draft.basePoints} onChange={(e) => setDraft({ ...draft, basePoints: e.target.value })} /></div></div>
      {draft.options.map((option, index) => <div className={styles.top} key={index}><div className={styles.field} style={{ flex: 1 }}><label htmlFor={`option-${index}`}>Alternativa {index + 1}</label><input id={`option-${index}`} value={option.text} onChange={(e) => setDraft({ ...draft, options: draft.options.map((item, itemIndex) => itemIndex === index ? { ...item, text: e.target.value } : item) })} required /></div><label><input type="radio" name="correct" checked={option.isCorrect} onChange={() => setDraft({ ...draft, options: draft.options.map((item, itemIndex) => ({ ...item, isCorrect: itemIndex === index })) })} /> Correta</label>{draft.options.length > 2 && <button type="button" onClick={() => setDraft({ ...draft, options: draft.options.filter((_, itemIndex) => itemIndex !== index) })}>Remover</button>}</div>)}
      <div className={styles.actions}><button type="button" disabled={draft.options.length >= 6} onClick={() => setDraft({ ...draft, options: [...draft.options, { text: "", isCorrect: false }] })}>Adicionar alternativa</button><button className={styles.button} disabled={busy}>{editing ? "Salvar pergunta" : "Adicionar pergunta"}</button></div></form>}
    <p className={styles.error} role="alert">{error}</p><p role="status">{saved}</p>
  </section></main>;
}
