"use client";
import {useParams,useRouter} from "next/navigation";
import {useCallback,useEffect,useMemo,useState} from "react";
import {api} from "../../../../lib/api";
import styles from "../../../auth.module.css";
const blank=()=>({prompt:"",durationSeconds:30,basePoints:1000,explanation:"",options:[{text:"",isCorrect:true},{text:"",isCorrect:false}]});
const snap=(meta,draft,editing)=>JSON.stringify({meta:{title:meta.title.trim(),description:meta.description.trim()},draft:{...draft,prompt:draft.prompt.trim(),explanation:draft.explanation.trim(),durationSeconds:Number(draft.durationSeconds),basePoints:Number(draft.basePoints),options:draft.options.map(({id,text,isCorrect})=>({id,text:text.trim(),isCorrect}))},editing});
export default function Editor(){
 const{id}=useParams(),router=useRouter();
 const[quiz,setQuiz]=useState(null),[meta,setMeta]=useState({title:"",description:""}),[draft,setDraft]=useState(blank()),[editing,setEditing]=useState(null),[baseline,setBaseline]=useState(""),[leaveOpen,setLeaveOpen]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(""),[busy,setBusy]=useState(false);
 const current=useMemo(()=>snap(meta,draft,editing),[meta,draft,editing]),dirty=Boolean(baseline&&current!==baseline);
 const load=useCallback(async()=>{try{const next=(await api(`/quizzes/${id}`)).quiz,nextMeta={title:next.title,description:next.description||""},nextDraft=blank();setQuiz(next);setMeta(nextMeta);setDraft(nextDraft);setEditing(null);setBaseline(snap(nextMeta,nextDraft,null));}catch(e){if(e.status===401)router.replace("/login");else setError(e.message);}},[id,router]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
 useEffect(()=>{if(!dirty)return;const warn=(event)=>{event.preventDefault();event.returnValue="";};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
 async function act(fn,reset=true){setBusy(true);setError("");setSaved("");try{await fn();if(reset)await load();setSaved("Alterações salvas.");return true;}catch(e){setError(e.details?.map((d)=>`${d.path}: ${d.message}`).join(" ")||e.message);return false;}finally{setBusy(false);}}
 function saveMeta(event){event.preventDefault();return act(()=>api(`/quizzes/${id}`,{method:"PATCH",body:JSON.stringify({...meta,description:meta.description||null,version:quiz.version})}));}
 function saveQuestion(event){event.preventDefault();const payload={...draft,durationSeconds:Number(draft.durationSeconds),basePoints:Number(draft.basePoints),...(editing?{version:quiz.version}:{})};return act(()=>api(`/quizzes/${id}/questions${editing?`/${editing}`:""}`,{method:editing?"PATCH":"POST",body:JSON.stringify(payload)}));}
 function edit(question){const next={prompt:question.prompt,durationSeconds:question.durationSeconds,basePoints:question.basePoints,explanation:question.explanation||"",options:question.options.map(({id,text,isCorrect})=>({id,text,isCorrect}))};setEditing(question.id);setDraft(next);setBaseline(snap(meta,next,question.id));}
 function moveOption(index,delta){const options=[...draft.options];[options[index],options[index+delta]]=[options[index+delta],options[index]];setDraft({...draft,options});}
 function moveQuestion(index,delta){const ids=quiz.questions.map((question)=>question.id);[ids[index],ids[index+delta]]=[ids[index+delta],ids[index]];return act(()=>api(`/quizzes/${id}/questions/reorder`,{method:"POST",body:JSON.stringify({ids})}));}
 if(!quiz)return <main className={styles.shell}><p>{error||"Carregando editor…"}</p></main>;
 const editable=quiz.status==="DRAFT";
 return <main className={styles.shell}><section className={styles.card} style={{width:"min(100%,900px)"}}>
  <header className={styles.top}><div><button className={styles.linkButton} onClick={()=>dirty?setLeaveOpen(true):router.push("/painel")}>← Painel</button><h1>{quiz.title}</h1><p>{quiz.status} · versão {quiz.version}</p><p role="status">{dirty?"Alterações não salvas.":saved}</p></div><div className={styles.actions}>{editable?<button className={styles.button} disabled={busy||dirty} onClick={()=>act(()=>api(`/quizzes/${id}/publish`,{method:"POST",body:"{}"}))}>Publicar</button>:<button onClick={()=>act(()=>api(`/quizzes/${id}/unpublish`,{method:"POST",body:"{}"}))}>Despublicar</button>}<button disabled={!editable||busy} onClick={()=>{if(confirm("Excluir este quiz?"))act(async()=>{await api(`/quizzes/${id}`,{method:"DELETE",body:"{}"});router.replace("/painel");},false);}}>Excluir</button></div></header>
  <form className={styles.form} onSubmit={saveMeta}><div className={styles.field}><label htmlFor="title">Título</label><input id="title" value={meta.title} onChange={(e)=>setMeta({...meta,title:e.target.value})} disabled={!editable} required/></div><div className={styles.field}><label htmlFor="description">Descrição</label><textarea id="description" value={meta.description} onChange={(e)=>setMeta({...meta,description:e.target.value})} disabled={!editable}/></div><button className={styles.button} disabled={!editable||busy}>Salvar dados</button></form>
  <h2>Perguntas</h2>{quiz.questions.map((question,index)=><article key={question.id}><div className={styles.top}><div><strong>{index+1}. {question.prompt}</strong><p>{question.durationSeconds}s · {question.basePoints} pontos · {question.options.length} alternativas</p></div><div className={styles.actions}><button disabled={!editable||index===0} onClick={()=>moveQuestion(index,-1)}>Subir pergunta</button><button disabled={!editable||index===quiz.questions.length-1} onClick={()=>moveQuestion(index,1)}>Descer pergunta</button><button disabled={!editable} onClick={()=>edit(question)}>Editar</button><button disabled={!editable} onClick={()=>{if(confirm("Excluir pergunta?"))act(()=>api(`/quizzes/${id}/questions/${question.id}`,{method:"DELETE",body:"{}"}));}}>Excluir</button></div></div></article>)}
  {editable&&<form className={styles.form} onSubmit={saveQuestion}><h2>{editing?"Editar pergunta":"Nova pergunta"}</h2><div className={styles.field}><label htmlFor="prompt">Enunciado</label><input id="prompt" value={draft.prompt} onChange={(e)=>setDraft({...draft,prompt:e.target.value})} required/></div><div className={styles.top}><div className={styles.field}><label htmlFor="duration">Duração</label><input id="duration" type="number" min="5" max="120" value={draft.durationSeconds} onChange={(e)=>setDraft({...draft,durationSeconds:e.target.value})}/></div><div className={styles.field}><label htmlFor="points">Pontos</label><input id="points" type="number" min="100" max="10000" value={draft.basePoints} onChange={(e)=>setDraft({...draft,basePoints:e.target.value})}/></div></div>
   {draft.options.map((option,index)=><div className={styles.top} key={option.id||`new-${index}`}><div className={styles.field} style={{flex:1}}><label htmlFor={`option-${index}`}>Alternativa {index+1}</label><input id={`option-${index}`} value={option.text} onChange={(e)=>setDraft({...draft,options:draft.options.map((item,i)=>i===index?{...item,text:e.target.value}:item)})} required/></div><label><input type="radio" name="correct" checked={option.isCorrect} onChange={()=>setDraft({...draft,options:draft.options.map((item,i)=>({...item,isCorrect:i===index}))})}/> Correta</label><div className={styles.actions}><button type="button" aria-label={`Mover alternativa ${index+1} para cima`} disabled={index===0} onClick={()=>moveOption(index,-1)}>Subir</button><button type="button" aria-label={`Mover alternativa ${index+1} para baixo`} disabled={index===draft.options.length-1} onClick={()=>moveOption(index,1)}>Descer</button>{draft.options.length>2&&<button type="button" onClick={()=>setDraft({...draft,options:draft.options.filter((_,i)=>i!==index)})}>Remover</button>}</div></div>)}
   <div className={styles.actions}><button type="button" disabled={draft.options.length>=6} onClick={()=>setDraft({...draft,options:[...draft.options,{text:"",isCorrect:false}]})}>Adicionar alternativa</button><button className={styles.button} disabled={busy}>{editing?"Salvar pergunta":"Adicionar pergunta"}</button></div></form>}
  <p className={styles.error} role="alert">{error}</p>{leaveOpen&&<div className={styles.dialogBackdrop}><div className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="leave-title"><h2 id="leave-title">Descartar alterações?</h2><p>Você tem alterações não salvas. Deseja descartá-las e sair?</p><div className={styles.actions}><button autoFocus onClick={()=>setLeaveOpen(false)}>Permanecer</button><button className={styles.button} onClick={()=>router.push("/painel")}>Descartar e sair</button></div></div></div>}
 </section></main>;
}
