import { createHash, randomBytes } from "node:crypto";
import { z } from "zod";
import { DomainError } from "../errors/domain-error.js";
import { transaction } from "../repositories/transaction.js";
import { hashSecret, verifySecret } from "./tokens.js";
import { snapshotFromQuiz } from "../mappers/snapshot.js";
import { sessionDTO } from "../mappers/snapshot.js";
import { hashToken } from "./tokens.js";

const nameSchema = z.string().trim().min(2).max(100);
const emailSchema = z.string().trim().max(254).pipe(z.email()).transform((value) => value.toLowerCase());
const passwordSchema = z.string().min(10).max(128).refine((v) => /[A-Za-z]/.test(v) && /\d/.test(v), "A senha deve conter letra e número.");
const quizSchema = z.object({ title: z.string().trim().min(1).max(300), description: z.string().trim().max(10000).nullable().optional().default(null), version: z.number().int().positive().optional() }).strict();
const optionSchema = z.object({ id: z.uuid().optional(), text: z.string().trim().min(1).max(1000), isCorrect: z.boolean() }).strict();
const questionSchema = z.object({ prompt: z.string().trim().min(1).max(5000), durationSeconds: z.number().int().min(5).max(120), basePoints: z.number().int().min(100).max(10000), explanation: z.string().trim().max(10000).nullable().optional().default(null), options: z.array(optionSchema).min(2).max(6) }).strict().superRefine((q, ctx) => { if (q.options.filter((o) => o.isCorrect).length !== 1) ctx.addIssue({ code: "custom", path: ["options"], message: "Exatamente uma resposta correta é obrigatória." }); });
const SESSION_MS = 8 * 60 * 60 * 1000;
const digest = (token) => createHash("sha256").update(token).digest("hex");
const userDTO = ({ id, name, email, createdAt }) => ({ id, name, email, createdAt });
const quizDTO = (quiz, full = false) => ({ id: quiz.id, title: quiz.title, description: quiz.description, status: quiz.status, version: quiz.version, questionCount: quiz.questions?.length ?? quiz._count?.questions ?? 0, createdAt: quiz.createdAt, updatedAt: quiz.updatedAt, publishedAt: quiz.publishedAt, ...(full ? { questions: quiz.questions.map((q) => ({ id: q.id, prompt: q.prompt, durationSeconds: q.durationSeconds, basePoints: q.basePoints, explanation: q.explanation, position: q.position, options: q.options.map((o) => ({ id: o.id, text: o.text, isCorrect: o.isCorrect, position: o.position })) })) } : {}) });

function parse(schema, value, code = "INVALID_PAYLOAD") { const result = schema.safeParse(value); if (!result.success) throw new DomainError(code, code, result.error.issues.map((issue) => ({ code: "INVALID", path: issue.path.join("."), message: issue.message }))); return result.data; }
async function owned(db, ownerId, id) { const quiz = await db.quiz.findFirst({ where: { id, ownerId }, include: { questions: { orderBy: { position: "asc" }, include: { options: { orderBy: { position: "asc" } } } } } }); if (!quiz) throw new DomainError("NOT_FOUND"); return quiz; }
async function sessionResult(db, owner, replace = true) { if (replace) await db.organizerSession.deleteMany({ where: { ownerId: owner.id } }); const token = randomBytes(32).toString("hex"); const expiresAt = new Date(Date.now() + SESSION_MS); await db.organizerSession.create({ data: { ownerId: owner.id, tokenHash: digest(token), expiresAt } }); return { token, expiresAt, user: userDTO(owner) }; }

export function createOrganizerService(client) {
  return {
    normalizeEmail: (email) => parse(emailSchema, email),
    validatePassword: (password) => parse(passwordSchema, password),
    register(input) { return transaction(client, async (tx) => { const data = parse(z.object({ name: nameSchema, email: emailSchema, password: passwordSchema }).strict(), input); const owner = await tx.organizer.create({ data: { name: data.name, email: data.email, passwordHash: await hashSecret(data.password) } }); return sessionResult(tx, owner); }, "EMAIL_CONFLICT"); },
    login(input) { return transaction(client, async (tx) => { const data = parse(z.object({ email: emailSchema, password: z.string().max(128) }).strict(), input); const owner = await tx.organizer.findUnique({ where: { email: data.email } }); if (!owner || !(await verifySecret(data.password, owner.passwordHash).catch(() => false))) throw new DomainError("INVALID_CREDENTIALS"); return sessionResult(tx, owner); }); },
    async authenticate(token) { if (!token) return null; const row = await client.organizerSession.findUnique({ where: { tokenHash: digest(token) }, include: { owner: true } }); if (!row || row.expiresAt <= new Date()) { if (row) await client.organizerSession.delete({ where: { id: row.id } }); return null; } return userDTO(row.owner); },
    async logout(token) { if (token) await client.organizerSession.deleteMany({ where: { tokenHash: digest(token) } }); },
    listQuizzes: async (ownerId) => (await client.quiz.findMany({ where: { ownerId }, include: { _count: { select: { questions: true } } }, orderBy: [{ updatedAt: "desc" }, { id: "asc" }] })).map(quizDTO),
    async getQuiz(ownerId, id) { return quizDTO(await owned(client, ownerId, id), true); },
    createQuiz(ownerId, input) { const data = parse(quizSchema.omit({ version: true }), input); return client.quiz.create({ data: { ownerId, title: data.title, description: data.description } }).then(quizDTO); },
    updateQuiz(ownerId, id, input) { const data = parse(quizSchema, input); return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, id); if (quiz.status !== "DRAFT") throw new DomainError("QUIZ_NOT_DRAFT"); if (data.version && data.version !== quiz.version) throw new DomainError("CONFLICT"); const result = await tx.quiz.updateMany({ where: { id, ownerId, version: quiz.version }, data: { title: data.title, description: data.description, version: { increment: 1 } } }); if (result.count !== 1) throw new DomainError("CONFLICT"); return quizDTO(await owned(tx, ownerId, id), true); }); },
    addQuestion(ownerId, quizId, input) { const data = parse(questionSchema, input); return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, quizId); if (quiz.status !== "DRAFT") throw new DomainError("QUIZ_NOT_DRAFT"); const position = quiz.questions.length + 1; await tx.question.create({ data: { quizId, position, prompt: data.prompt, durationSeconds: data.durationSeconds, basePoints: data.basePoints, explanation: data.explanation, options: { create: data.options.map((o, i) => ({ text: o.text, isCorrect: o.isCorrect, position: i + 1 })) } } }); await tx.quiz.update({ where: { id: quizId }, data: { version: { increment: 1 } } }); return quizDTO(await owned(tx, ownerId, quizId), true); }); },
    updateQuestion(ownerId, quizId, questionId, input) { const data = parse(questionSchema, input); return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, quizId); if (quiz.status !== "DRAFT" || !quiz.questions.some((q) => q.id === questionId)) throw new DomainError(quiz.status !== "DRAFT" ? "QUIZ_NOT_DRAFT" : "NOT_FOUND"); await tx.questionOption.deleteMany({ where: { questionId } }); await tx.question.update({ where: { id: questionId }, data: { prompt: data.prompt, durationSeconds: data.durationSeconds, basePoints: data.basePoints, explanation: data.explanation, options: { create: data.options.map((o, i) => ({ text: o.text, isCorrect: o.isCorrect, position: i + 1 })) } } }); await tx.quiz.update({ where: { id: quizId }, data: { version: { increment: 1 } } }); return quizDTO(await owned(tx, ownerId, quizId), true); }); },
    deleteQuestion(ownerId, quizId, questionId) { return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, quizId); if (quiz.status !== "DRAFT" || !quiz.questions.some((q) => q.id === questionId)) throw new DomainError(quiz.status !== "DRAFT" ? "QUIZ_NOT_DRAFT" : "NOT_FOUND"); await tx.question.delete({ where: { id: questionId } }); const remaining = quiz.questions.filter((q) => q.id !== questionId); for (const [i, q] of remaining.entries()) await tx.question.update({ where: { id: q.id }, data: { position: -(i + 1) } }); for (const [i, q] of remaining.entries()) await tx.question.update({ where: { id: q.id }, data: { position: i + 1 } }); await tx.quiz.update({ where: { id: quizId }, data: { version: { increment: 1 } } }); }); },
    reorder(ownerId, quizId, ids) { return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, quizId); if (quiz.status !== "DRAFT" || !Array.isArray(ids) || ids.length !== quiz.questions.length || new Set(ids).size !== ids.length || ids.some((id) => !quiz.questions.some((q) => q.id === id))) throw new DomainError(quiz.status !== "DRAFT" ? "QUIZ_NOT_DRAFT" : "INVALID_ORDER"); for (const [i, id] of ids.entries()) await tx.question.update({ where: { id }, data: { position: -(i + 1) } }); for (const [i, id] of ids.entries()) await tx.question.update({ where: { id }, data: { position: i + 1 } }); await tx.quiz.update({ where: { id: quizId }, data: { version: { increment: 1 } } }); return quizDTO(await owned(tx, ownerId, quizId), true); }); },
    publish(ownerId, id) { return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, id); try { snapshotFromQuiz(quiz); } catch { throw new DomainError("QUIZ_INVALID", "QUIZ_INVALID", [{ code: "INCOMPLETE", path: "questions", message: "Complete todas as perguntas e alternativas antes de publicar." }]); } if (quiz.status === "PUBLISHED") return quizDTO(quiz, true); return quizDTO(await tx.quiz.update({ where: { id }, data: { status: "PUBLISHED", publishedAt: new Date(), version: { increment: 1 } }, include: { questions: { orderBy: { position: "asc" }, include: { options: { orderBy: { position: "asc" } } } } } }), true); }); },
    unpublish(ownerId, id) { return transaction(client, async (tx) => { await owned(tx, ownerId, id); return quizDTO(await tx.quiz.update({ where: { id }, data: { status: "DRAFT", publishedAt: null, version: { increment: 1 } } })); }); },
    remove(ownerId, id) { return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, id); if (quiz.status !== "DRAFT") throw new DomainError("QUIZ_NOT_DRAFT"); if (await tx.gameSession.count({ where: { quizId: id } })) throw new DomainError("QUIZ_IN_USE"); await tx.quiz.delete({ where: { id } }); }); },
    async publishedOwned(ownerId) { return (await client.quiz.findMany({ where: { ownerId, status: "PUBLISHED" }, include: { _count: { select: { questions: true } } }, orderBy: { updatedAt: "desc" } })).map(quizDTO); },
    async buildOwnedSnapshot(ownerId, id) { return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, id); if (quiz.status !== "PUBLISHED") throw new DomainError("QUIZ_NOT_PUBLISHED"); return snapshotFromQuiz(quiz); }); },
    createOwnedRoom(ownerId, quizId, roomCode, hostToken) { return transaction(client, async (tx) => { const quiz = await owned(tx, ownerId, quizId); if (quiz.status !== "PUBLISHED") throw new DomainError("QUIZ_NOT_PUBLISHED"); const snapshot = snapshotFromQuiz(quiz); return sessionDTO(await tx.gameSession.create({ data: { roomCode, quizId, quizSnapshot: snapshot, hostTokenHash: await hashToken(hostToken) } })); }, "ROOM_CODE_CONFLICT"); },
  };
}
